package com.makitaxi.utils;

public enum NotificationStatus {
    CREATED,
    CANCELLED_BY_PASSENGER,
    NO_AVAILABLE_DRIVERS,
    ALL_DRIVERS_DECLINED,
    CANCELLED_BY_DRIVER,
    CANCELLED_BY_DRIVER_WHILE_WAITING,
    ACCEPTED_BY_DRIVER,
    ACCEPTED_BY_PASSENGER,
    DECLINED_BY_PASSENGER,
    TIMEOUT,
    FINISHED,
    DRIVER_EXITED_APP,
    PASSENGER_EXITED_APP
}
